version: 2
jobs:
  build:
    docker:
    - image: circleci/python:2.7
    steps:
    - run: git clone https://github.com/StackStorm/st2docs.git ${HOME}/st2docs && cd ${HOME}/st2docs && BWC_BRANCH=${CIRCLE_BRANCH} make ewcdocs
