version: 2
jobs:
  build:
    docker:
    - image: circleci/python:2.7
    steps:
      - run:
          name: Clone st2docs and ST2
          command: |
            git clone https://github.com/StackStorm/st2docs.git .
            make .clone-st2
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "st2/requirements.txt" }}
      - run:
          name: Make EWC docs
          command: |
            BWC_BRANCH=${CIRCLE_BRANCH} make ewcdocs
      - save_cache:
          key: v1-dependency-cache-{{ checksum "st2/requirements.txt" }}
          paths:
            - ~/.cache/pip
